<?php

use Dredd\Hooks;

require __DIR__ . '/../../../vendor/autoload.php';

$app = require __DIR__ . '/../../../bootstrap/app.php';

$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

Hooks::beforeAll(function (&$transaction) {
    Illuminate\Support\Facades\Artisan::call('migrate:refresh', ['--seed' => true]);
});

Hooks::beforeEach(function (&$transaction) use ($app) {
    // Beware this transaction only works for the hooks itself.
    // If the API tests generated by Dredd make changes to the database,
    // they will not be rolled back. In that case, you must use migrations.
    $app->make('db')->beginTransaction();
});

Hooks::afterEach(function (&$transaction) use ($app) {
    $app->make('db')->rollback();
});

Hooks::before('/users > GET', function(&$transaction) {

    factory(\App\User::class)->create([
            'name' => 'Dom',
            'email' => 'ddelnano@gmail.com',
        ]
    );
});
