# My Api
## GET /users
+ Response 200 (application/json;charset=utf-8)
        {
            "users": [
                {
                    "name": "Dom",
                    "email": "ddelnano@gmail.com"
                }
            ]
        }

## GET /test
+ Response 200 (application/json;charset=utf-8)
        {
            "test": true
        }
